#!/bin/sh
#
# git-bpf -- A collection of Git extensions to provide high-level
# repository operations for Git Branch Per Feature (BPF) workflow.
#
# This project is an implementation of the Git BPF workflow
# described by Adam Dymitruk:
# 	http://dymitruk.com/blog/2012/02/05/branch-per-feature/
# And its source code is wildly inspired by gitflow tools source code:
#    https://github.com/nvie/gitflow
# 
# Feel free to contribute to this project at:
#    https://github.com/cdue/gitbpf
#
# Copyright (c) 2015 Cédric Dué
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE
#


# First, find git-bpf install path in order to include common functions
if [ -z $GITBPF_DIR ]; then
	export GITBPF_DIR=$(dirname "$(which git-bpf | sed -e 's,\\,/,g')")
fi

# load common functionality
. "$GITBPF_DIR/gitbpf-common"

remote_name = $(git config --get gitbpf.remotename | sed  -e 's/\n$//g' | sed -e 's/\r$//g')
remote_url=$(git config --get remote.origin.url)

if [ -z $remote_name ] ; then
	warn "You have not configured the remote repository to be used by git-bpf. This is needed for rerere sharing. To use the 'origin' remote, run \n \`git config gitbpf.remotename 'origin'\`\n You can specify a remote name of your choosing."
elif [ -z $remote_url ]; then
	warn "You have not configured the remote url to be used by git-bpf. This is needed for rerere sharing. To set a remote url, run \n \`git remote add origin 'repo_url'\`\n"
else
	git bpf rerere pull -r $remote_name
	git bfp rerere push -r $remote_name
fi
